- title: 'BERT-HIT: A Transformer-Based Approach for Hardware Trojan Detection in Gate-Level Netlists'
  authors:
  - Lizi Zhang
  - Navid Nader Tehrani
  - Azadeh Davoodi
  - Rasit Onur Topaloglu
  image: images/BERT-HIT.jpg
  publisher: IEEE International Symposium on Quality Electronic Design
  date: '2026-04-08'

- title: 'ReBERT: LLM for Gate-Level to Word-Level Reverse Engineering, in Generative AI for Next Generation Computer Design'
  authors:
  - Lizi Zhang
  - Azadeh Davoodi
  - Rasit Onur Topaloglu
  image: images/ReBERT.jpg
  publisher: Springer Nature
  date: '2026-06-06'
  
- id: doi:10.1109/COINS65080.2025.11125725
  image: images/CADI.png
  
- title: 'DNNP: An Automated, Hybrid Framework for Neural Network Pruning on Edge Devices'
  authors:
  - Robert Viramontes
  - Cheng-En Wu
  - Azadeh Davoodi
  - Yu-Hen Hu
  publisher: Poster at 7th Annual Conference on Machine Learning and Systems (MLSys)
  date: '2024-05-13'

- id: doi:10.1109/SMARTCOMP65954.2025.00106
  image: images/FreDDI.jpg
  
- id: doi:10.1145/3658617.3697592
  image: images/static-ir-drop.png

- id: doi:10.23919/DATE64628.2025.10993097
  image: images/BPC.jpg
  
- id: doi:10.1145/3670474.3685939
  image: images/artifact.jpg
  
- title: 'Power-driven global routing for MSV domains'
  authors:
  - Tai-Hsuan Wu
  - Azadeh Davoodi
  - Jeffrey T. Linderoth
  link: https://ieeexplore.ieee.org/document/5763077
  publisher: IEEE/ACM Design, Automation & Test In Europe Conference & Exhibition (DATE)
  date: '2011-03-14'
  doi: 10.1109/DATE.2011.5763077
  
  
- title: 'A hybrid approach for fast and accurate trace signal selection for post-silicon debug'
  authors:
  - Min Li
  - Azadeh Davoodi  
  link: https://ieeexplore.ieee.org/document/6513557
  publisher: IEEE/ACM Design, Automation & Test In Europe Conference & Exhibition (DATE)
  date: '2013-03-23'
  doi: 10.7873/DATE.2013.111
  
- title: 'A procedure for improving the distribution of congestion in global routing'
  authors:
  - Tai-Hsuan Wu
  - Jeffrey T. Linderoth
  - Azadeh Davoodi  
  link: https://ieeexplore.ieee.org/abstract/document/7459314
  publisher: IEEE/ACM Design, Automation & Test In Europe Conference & Exhibition (DATE)
  date: '2016-03-14'
  isbn: 978-3-9815-3707-9
  
- title: 'Technology Mapping with All Spin Logic'
  authors:
  - Boyu Zhang
  - Azadeh Davoodi  
  link: https://ieeexplore.ieee.org/document/7927123
  publisher: IEEE/ACM Design, Automation & Test In Europe Conference & Exhibition (DATE)
  date: '2017-03-27'
  doi: 10.23919/DATE.2017.7927123

- title: 'Simultaneous floorplanning and binding: A probabilistic approach'
  authors:
  - Azadeh Davoodi
  - Ankur Srivastava
  publisher: IEEE/ACM International Workshop on Logic & Synthesis (IWLS)
  date: '2004-06-01'

- title: 'Efficient stochastic pruning for variability-driven dual-Vth leakage optimization'
  authors:
  - Azadeh Davoodi
  - Ankur Srivastava
  publisher: IEEE/ACM International Workshop on Logic & Synthesis (IWLS)
  date: '2005-06-01'

- title: 'Variability driven buffer insertion considering correlations'
  authors:
  - Azadeh Davoodi
  - Ankur Srivastava
  publisher: IEEE/ACM International Workshop on Logic & Synthesis (IWLS)
  date: '2005-06-01'
  
- title: 'Variability driven gate sizing for binning yield optimization'
  authors:
  - Azadeh Davoodi
  - Ankur Srivastava
  publisher: IEEE/ACM International Workshop on Logic & Synthesis (IWLS) 
  date: '2006-06-01'
  
- title: 'A dual-Vt assignment algorithm of SRAM array considering process-induced Vt variations'
  authors:
  - Jungseob Lee
  - Azadeh Davoodi
  publisher: IEEE/ACM International Workshop on Logic & Synthesis (IWLS)
  date: '2007-06-01'
  
- title: 'SynECO: Technology remapping with incremental constrained placement and exact timing estimation'
  authors:
  - Anuj Kumar
  - Azadeh Davoodi
  publisher: IEEE/ACM International Workshop on Logic & Synthesis (IWLS)
  date: '2008-06-01'
  
- title: 'A parallel and randomized algorithm for large-scale discrete dual-Vt assignment and continuous gate sizing'
  authors:
  - Tai-Hsuan Wu
  - Lin Xie
  - Azadeh Davoodi
  publisher: IEEE/ACM International Workshop on Logic & Synthesis (IWLS) 
  date: '2008-06-01'
  
- title: 'Representative path selection for post-silicon timing prediction under variability'
  authors:
  - Lin Xie
  - Azadeh Davoodi
  publisher: ACM Workshop on Timing Issues in the Specification of Digital Systems (TAU)
  date: '2010-04-01'

- title: 'Automation tools for post-silicon debug of timing errors'
  authors:
  - Azadeh Davoodi
  publisher: IEEE International Workshop on Microprocessor Test and Verification (MTV)
  date: '2010-12-01'

- title: 'A hybrid approach for fast and accurate trace signal selection for post-silicon debug'
  authors:
  - Min Li
  - Azadeh Davoodi
  publisher: IEEE International Workshop on Microprocessor Test and Verification (MTV)
  date: '2012-12-01'

- title: 'Online and operand-aware detection of failures by utilizing false alarm vectors'
  authors:
  - Amir Yazdanbakhsh
  - David Palframan
  - Azadeh Davoodi
  - Nam Sung Kim
  - Mikko Lipasti
  publisher: IEEE/ACM International Workshop on Logic & Synthesis (IWLS)
  date: '2013-06-01'

- title: 'On Neural Networks for Automatic Test Pattern Generation'
  authors:
  - Lizi Zhang
  - Azadeh Davoodi
  publisher: IEEE/ACM International Workshop on Logic & Synthesis (IWLS)
  date: '2024-06-06'
  
- title: 'A Systematic Framework for Opportunistic Pruning of Deep Neural Networks on Edge Devices'
  authors:
  - Robert Viramontes
  - Azadeh Davoodi
  publisher: IEEE/ACM International Workshop on Logic & Synthesis (IWLS)
  date: '2024-06-06'

- id: doi:arXiv:2408.03292v1
- id: doi:10.1109/SMARTCOMP61445.2024.00081
- id: doi:10.23919/DATE48585.2020.9116488
- id: doi:10.1016/j.vlsi.2022.10.013
- id: doi:10.1109/ISQED57927.2023.10129343
- id: doi:10.48550/arXiv.2312.16904
- id: doi:10.1145/3520126
- id: doi:10.1109/ASP-DAC52403.2022.9712496
- id: doi:10.1109/MDAT.2020.2977065
- id: doi:10.1109/TCAD.2020.3033750
- id: doi:10.1145/3394885.3431600
- id: doi:10.23919/DATE51398.2021.9473972
- id: doi:10.1109/ICCAD51958.2021.9643484
- id: doi:10.1109/ISVLSI51109.2021.00033
- id: doi:10.1109/COINS49042.2020.9191636
- id: doi:10.1109/DAC18072.2020.9218741
- id: doi:10.1016/J.VLSI.2019.08.003
- id: doi:10.1109/TVLSI.2019.2929710
- id: doi:10.1109/ISQED.2019.8697843
- id: doi:10.1007/978-3-319-98116-1_5
- id: doi:10.1109/JETCAS.2018.2833383
- id: doi:10.1109/ASPDAC.2018.8297345
- id: doi:10.1145/3195970.3195991
- id: doi:10.1145/3194554.3194579
- id: doi:10.1109/ICCD.2018.00033
- id: doi:10.1109/TCAD.2017.2695889
- id: doi:10.1109/TVLSI.2017.2748018
- id: doi:10.1109/ASPDAC.2017.7858351
- id: doi:10.1145/2966986.2967006
- id: doi:10.48550/arXiv.2012.02530
- id: doi:10.48550/arXiv.1908.03266
- id: doi:10.48550/arXiv.1811.00056
- id: doi:10.1007/978-3-319-68511-3_9
- id: doi:10.48550/arXiv.1811.04151
- id: doi:10.1145/3061639.3062335
- id: doi:10.1145/3036669.3036676
- id: doi:10.23919/DATE.2017.7927123
- id: doi:10.1109/ASPDAC.2016.7428040
- id: doi:10.1145/2744769.2744878
- id: doi:10.1145/2742060.2742097
- id: doi:10.1145/2541012.2541014
- id: doi:10.1109/MDAT.2013.2255913
- id: doi:10.1109/TVLSI.2012.2205717
- id: doi:10.1155/2013/905493
- id: doi:10.7873/DATE.2013.111
- id: doi:10.1145/2451916.2451940
- id: doi:10.1109/ISQED.2015.7085480
- id: doi:10.1109/ASPDAC.2014.6742963
- id: doi:10.1109/TCAD.2014.2307533
- id: doi:10.1109/TCAD.2012.2187206
- id: doi:10.1145/2228360.2228487
- id: doi:10.1109/DATE.2012.6176698
- id: doi:10.1109/DATE.2012.6176726
- id: doi:10.1109/ICCAD.2011.6105337
- id: doi:10.1109/TCAD.2010.2072670
- id: doi:10.1109/TCAD.2010.2066030
- id: doi:10.1145/1840845.1840935
- id: doi:10.1145/1837274.1837323
- id: doi:10.1145/1837274.1837344
- id: doi:10.1145/1837274.1837371
- id: doi:10.1109/ASPDAC.2010.5419815
- id: doi:10.1109/TCAD.2009.2028682
- id: doi:10.1109/TCAD.2009.2018874
- id: doi:10.1145/1594233.1594247
- id: doi:10.1145/1629911.1629999
- id: doi:10.1109/VTS.2009.17
- id: doi:10.1109/ASPDAC.2009.4796493
- id: doi:10.1109/ISQED.2008.4479718
- id: doi:10.1145/1393921.1393937
- id: doi:10.1145/1146909.1147152
- id: doi:10.1049/iet-cds:20070189
- id: doi:10.1109/ICCAD.2008.4681571
- id: doi:10.1109/ICCAD.2008.4681559
- id: doi:10.1109/ICCD.2008.4751915
- id: doi:10.1145/1393921.1393937
- id: doi:10.1109/ISCAS.2008.4541484
- id: doi:10.1109/ISQED.2008.4479718
- id: doi:10.1109/ISQED.2008.4479825
- id: doi:10.1109/ICCD.2007.4601886
- id: doi:10.1109/ISCAS.2007.377982
- id: doi:10.1109/VLSID.2007.176
- id: doi:10.1109/TCAD.2006.882529
- id: doi:10.1155/ES/2006/31605
- id: doi:10.1109/TCAD.2005.855885
- id: doi:10.1145/1124713.1124718
- id: doi:10.1145/1146909.1147152
- id: doi:10.1145/1123008.1123013
- id: doi:10.1109/TVLSI.2005.853618
- id: doi:10.1109/LPE.2003.1231851
- id: doi:10.1145/1059876.1059884
- id: doi:10.1109/ICCD.2005.114
  date: '2005-10-02'
- id: doi:10.1145/1077603.1077641
- id: doi:10.1109/ASPDAC.2005.1466478
  date: '2005-01-21'
- id: doi:10.1145/1120725.1120952
- id: doi:10.1109/TVLSI.2004.834235
- id: doi:10.1109/ICCAD.2004.1382612
  date: '2004-10-11'
- id: doi:10.1109/ICCAD.2004.1382666
  date: '2004-10-11'
- id: doi:10.1109/ICCAD.2004.1382623
  date: '2004-10-11'
- id: doi:10.1145/988952.988957
- id: doi:10.1109/ICCAD.2003.159738
- id: doi:10.1145/1059876.1059884
- id: doi:10.1109/LPE.2003.1231852
  date: '2003-08-27'



